data:
  data_dir: "./data/labeled"
  batch_size: 8
  image_size: 256
  num_workers: 10
  train_val_split_ratio: 0.8
  prefetch_factor: 2
  persistent_workers: true
  seed: 42

model:
  input_nc: 4
  output_nc: 3
  ngf: 64
  ndf: 64
  n_blocks: 8
  n_layers: 3
  num_D: 4

optimizer:
  lr_g: 0.0006
  lr_d: 0.0004
  beta1: 0.5
  beta2: 0.999

scheduler:
  eta_min: 1e-6

loss:
  gan_weight: 1.5
  l1_weight: 165.0

system:
  device: "cuda"
  precision: 32
  deterministic: false
  benchmark: false
  use_amp: false
  max_epochs: 200
  checkpoints_dir: "./checkpoints/pix2pix/"
  output_dir: "./output/pix2pix/"
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  accumulate_grad_batches: 1
  tb_version: 'pix2pix'